org: prasanna9417
app: serverless-auth
service: sls-auth-verifyOTP

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  apiGateway:
    restApiId:
      "Fn::ImportValue": SLSSharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": SLSSharedGW-rootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  signIn:
    handler: lambda/index.signIn
    events:
      - http:
          path: signin
          method: post
          cors: true

 