org: prasanna9417
app: serverless-auth
service: sls-auth-googleSignIn

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  apiGateway:
    restApiId:
      "Fn::ImportValue": SLSSharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": SLSSharedGW-rootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  googleSignIn-authorizer:
    handler: authorizer/index.googleOAuth2
  googleSignIn:
    handler: lambda/index.googleSignIn
    events:
      - http:
          path: googlesignin
          method: post
          cors: true
          authorizer: googleSignIn-authorizer

 